// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsJU2xIYDaTPU4a7QxJdvf8qI9sCjp9tM',
    appId: '1:945001883969:android:b8a2ae5506671c47b3d9c0',
    messagingSenderId: '945001883969',
    projectId: 'astro-c6639',
    databaseURL: 'https://astro-c6639-default-rtdb.firebaseio.com',
    storageBucket: 'astro-c6639.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ZO0xVwfV2CRdtbRLkQdHtg3FdrTwhcI',
    appId: '1:945001883969:ios:0bd8ad8a552eb509b3d9c0',
    messagingSenderId: '945001883969',
    projectId: 'astro-c6639',
    databaseURL: 'https://astro-c6639-default-rtdb.firebaseio.com',
    storageBucket: 'astro-c6639.firebasestorage.app',
    androidClientId: '945001883969-qqvgtq3k9flrc2mo3jba649q6ptlvq7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.asApp',
  );

}